version: '2'

services:
        db:
                image: postgres
        api:
                build: ./backend
                command: bash -c "python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
                volumes:
                        - ./backend:/code
                expose:
                        - "8080"
                depends_on:
                        - db
                restart: always
        nginx:
                image: nginx
                volumes:
                        - ./frontend/dist:/var/www/html
                        - ./backend/static:/var/www/static
                        - ./config/nginx:/etc/nginx/conf.d
                ports:
                        - "80:8000"
                depends_on:
                        - api
                restart: always
